version: '3'
services:
  wordpress_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
    volumes:
      - ./vanilla/db:/var/lib/mysql
    networks:
      - back
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - back
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: examplepass
      PMA_HOST: wordpress_db
  wordpress:
    image: wordpress:latest
    networks:
      - front
      - back
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: wordpress_db
    volumes:
      - ./vanilla/wordpress-data:/var/www/html
      - ./vanilla/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
networks:
  front:
  back: